export const EVENTS=[
    {
        eventId:1,
        eventName:'Event-ABC',
        eventDate:'23-May-2020',
        availableSeats:23,
        image:'assets/images/image1.png'
    },
    {
        eventId:2,
        eventName:'EVENT-DEF',
        eventDate:'23-May-2020',
        availableSeats:23,
        image:'assets/images/image2.png'
    },
    {
        eventId:3,
        eventName:'EVENT-GHI',
        eventDate:'23-May-2020',
        availableSeats:0,
        image:'assets/images/image3.png'
    },
    {
        eventId:4,
        eventName:'EVENT-JKL',
        eventDate:'23-May-2020',
        availableSeats:23,
        image:'assets/images/image4.png'
    },
    {
        eventId:5,
        eventName:'EVENT-MNO',
        eventDate:'23-May-2020',
        availableSeats:10,
        image:'assets/images/image5.png'
    },
    {
        eventId:6,
        eventName:'EVENT-PQR',
        eventDate:'23-May-2020',
        availableSeats:0,
        image:'assets/images/image6.png'
    },
    {
        eventId:7,
        eventName:'EVNT-STU',
        eventDate:'23-May-2020',
        availableSeats:15,
        image:'assets/images/image7.png'
    },
    {
        eventId:8,
        eventName:'EVNT-VWXY',
        eventDate:'23-May-2020',
        availableSeats:5,
        image:'assets/images/image8.png'
    }
]